"""
DataStore — single in-memory store for all application state.
Follows the global contract schema:
  { id, timestamp, src_ip, dst_ip, protocol, packets_per_sec,
    bytes, flow_duration, attack_type, confidence, severity }
severity ∈ {Low, Medium, High, Critical}
BENIGN traffic → attack_type = "BENIGN"
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any


MAX_EVENTS = 10_000


@dataclass
class DataStore:
    # Rolling list of traffic/attack events (max 10,000)
    events: list[dict[str, Any]] = field(default_factory=list)

    # Alert records generated by the alert engine
    alerts: list[dict[str, Any]] = field(default_factory=list)

    # Blacklisted source IPs
    blacklist: set[str] = field(default_factory=set)

    # Per-IP risk scores (raw metadata)
    risk_scores: dict[str, dict[str, Any]] = field(default_factory=dict)

    # Simulation state
    sim_running: bool = False
    sim_pointer: int = 0

    # ── helpers ───────────────────────────────────────────────────────────────

    def add_event(self, event: dict[str, Any]) -> None:
        """Append a new event, enforcing the rolling 10k cap."""
        self.events.append(event)
        if len(self.events) > MAX_EVENTS:
            self.events = self.events[-MAX_EVENTS:]

    def add_alert(self, alert: dict[str, Any]) -> None:
        self.alerts.append(alert)

    def add_to_blacklist(self, ip: str) -> None:
        self.blacklist.add(ip)

    def remove_from_blacklist(self, ip: str) -> None:
        self.blacklist.discard(ip)

    def set_risk_score(self, ip: str, score: float) -> None:
        if ip not in self.risk_scores or not isinstance(self.risk_scores[ip], dict):
            self.risk_scores[ip] = {
                "raw_score": score,
                "score": score * 100,
                "event_count": 0,
                "attack_types": {}
            }
        else:
            self.risk_scores[ip]["score"] = max(0.0, min(100.0, score * 100))

    def reset(self) -> None:
        """Clear all state (useful between simulations)."""
        self.events.clear()
        self.alerts.clear()
        self.blacklist.clear()
        self.risk_scores.clear()
        self.sim_running = False
        self.sim_pointer = 0


# ── Singleton instance ─────────────────────────────────────────────────────────
data_store = DataStore()
