"""
alerts.py — Alert management routes.
GET /api/alerts  →  Returns DataStore.alerts list.

Alert shape: { id, timestamp, src_ip, attack_type, severity, count }
"""

from fastapi import APIRouter
from services.data_store import data_store

router = APIRouter(tags=["alerts"])


@router.get("/alerts")
async def list_alerts():
    """Return all alerts generated by the alert engine."""
    return data_store.alerts
